name: Deploy HTML via SSH
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Skip broken submodules
        run: git submodule update --init --force --recursive || true

      # 通过 SSH 同步到服务器
      - name: Deploy via RSYNC
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
